// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huhpvawveowlezmbfoww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1aHB2YXd2ZW93bGV6bWJmb3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3Mzg2NDQsImV4cCI6MjA4NjMxNDY0NH0.B7JjKbpm4YgPDpGyjBmL9cYQNfRHNzpf17fqgeGzH8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});